# reference https://helm.sh/docs/chart_template_guide/subcharts_and_globals/
apiVersion: v2
name: example-helm-go-microservice
description: An example Helm chart for Kubernetes Go microservices
type: application
version: 0.1.0
appVersion: "latest"
icon: "https://helm.sh/img/helm.svg"
dependencies:
  - name: service1
    version: 0.1.0
